# Generated by Django 6.0.2 on 2026-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_address_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
