# Generated by Django 6.0.2 on 2026-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_for',
            field=models.CharField(choices=[('OVERALL', 'Overall Clinic'), ('NURSE', 'Nursing'), ('DOCTOR', 'Doctor/Consultation'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy')], max_length=20),
        ),
    ]
