# Generated by Django 6.0.2 on 2026-03-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_report_report_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='custom_test_name',
            field=models.CharField(blank=True, help_text='For custom test types', max_length=200),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='test_name',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinic.labtesttype'),
        ),
    ]
