# Generated by Django 6.0.2 on 2026-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_labtesttype_alter_labrequest_custom_test_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('ADMIN', 'Admin')], default='RECEPTIONIST', max_length=20),
        ),
    ]
