# Generated by Django 6.0.2 on 2026-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(blank=True, help_text='Storage location e.g., Shelf A-1', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(blank=True, choices=[('JMS', 'JMS Pharmaceuticals'), ('PHARMACCESS', 'PharmAccess'), ('SPS', 'SPS Pharmaceuticals'), ('ABU', 'Abu Pharmaceutical'), ('LOCAL', 'Local Supplier'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier_contact',
            field=models.CharField(blank=True, help_text='Supplier contact info', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROP', 'Drop'), ('SOLUTION', 'Solution'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
