# Generated by Django 6.0.2 on 2026-03-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_remove_medicine_expiry_date_medicine_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='selling_price',
        ),
    ]
