# Generated by Django 6.0.3 on 2026-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_medicine_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
