# Generated by Django 6.0.2 on 2026-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_medicine_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
