# Generated by Django 6.0.2 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_patient_gender_alter_patient_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
