# Generated by Django 6.0.2 on 2026-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_patient_patient_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['status'], name='clinic_labr_status_dbd6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['date'], name='clinic_labr_date_bfbcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['completed_date'], name='clinic_labr_complet_52870c_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['visit', 'status'], name='clinic_labr_visit_i_263325_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='clinic_noti_user_id_5278b1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='clinic_noti_created_bf56ba_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['university_id'], name='clinic_pati_univers_582461_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='clinic_pati_full_na_eb83f4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_type'], name='clinic_pati_patient_9e6078_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='clinic_pati_created_088fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='clinic_visi_visit_d_b8e5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='clinic_visi_status_c81a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'visit_date'], name='clinic_visi_patient_18f14e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='clinic_visi_created_4db861_idx'),
        ),
    ]
