# Generated by Django 6.0.2 on 2026-03-17 13:39

import clinic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_labrequest_clinic_labr_status_dbd6dc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cannot_dispense',
            field=models.BooleanField(default=False, help_text='Mark as cannot dispense (out of stock, etc.)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cannot_dispense_reason',
            field=models.TextField(blank=True, help_text='Reason why cannot dispense'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[clinic.models.validate_avatar_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('ADMIN', 'Admin')], default='NURSE', max_length=20),
        ),
    ]
