# Generated by Django 6.0.2 on 2026-03-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_prescription_cannot_dispense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRED_MEDICINE', 'Expired Medicine'), ('NEW_VISIT', 'New Visit'), ('LAB_RESULT', 'Lab Result Ready'), ('COUNSELLING_COMPLETE', 'Counselling Complete'), ('SCAN_COMPLETE', 'Scan Complete'), ('SYSTEM', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('COUNSELLOR', 'Counsellor'), ('SCAN_TECHNICIAN', 'Scan Technician'), ('ADMIN', 'Admin')], default='NURSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITING_FOR_TRIAGE', 'Waiting for Triage'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('IN_LAB', 'In Lab'), ('IN_COUNSELLING', 'In Counselling'), ('IN_SCANNING', 'In Scanning'), ('WAITING_FOR_PHARMACY', 'Waiting for Pharmacy'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=25),
        ),
        migrations.CreateModel(
            name='CounsellingReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(blank=True, help_text='For custom counselling types', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('reason', models.TextField(blank=True, help_text='Reason for referral')),
                ('notes', models.TextField(blank=True, help_text="Counsellor's notes")),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_counselling', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_counselling', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_referrals', to='clinic.visit')),
                ('referral_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='clinic.counsellingtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='clinic_coun_status_f317df_idx'), models.Index(fields=['created_at'], name='clinic_coun_created_91193b_idx'), models.Index(fields=['completed_date'], name='clinic_coun_complet_a3c7ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(blank=True, help_text='For custom scan types', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical notes for the scan')),
                ('findings', models.TextField(blank=True, help_text='Scan findings/results')),
                ('technician_notes', models.TextField(blank=True, help_text='Technician notes')),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_scans', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_scans', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_referrals', to='clinic.visit')),
                ('scan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='clinic.scantype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='clinic_scan_status_02ee0f_idx'), models.Index(fields=['created_at'], name='clinic_scan_created_cb7da0_idx'), models.Index(fields=['completed_date'], name='clinic_scan_complet_1d252c_idx')],
            },
        ),
    ]
