# Generated by Django 6.0.3 on 2026-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_counsellingtype_scantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_for',
            field=models.CharField(choices=[('OVERALL', 'Overall Clinic'), ('NURSE', 'Nursing'), ('DOCTOR', 'Doctor/Consultation'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('COUNSELLING', 'Counselling'), ('SCANNING', 'Scanning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITING_FOR_TRIAGE', 'Waiting for Triage'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('IN_LAB', 'In Lab'), ('IN_COUNSELLING', 'In Counselling'), ('IN_SCANNING', 'In Sonography'), ('WAITING_FOR_PHARMACY', 'Waiting for Pharmacy'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=25),
        ),
    ]
